const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
const FETCH_POST_FAILURE = "FETCH_POST_FAILURE";
const CREATE_POST = "CREATE_POST";
const DELETE_POST = "DELETE_POST";
const UPDATE_POST = "UPDATE_POST";

export { FETCH_POST_SUCCESS, FETCH_POST_FAILURE, CREATE_POST, DELETE_POST, UPDATE_POST };
